[firebase]
type = "service_account"
project_id = "elena-36be5"
private_key_id = "3c1451f3d53262402fa0d79e94369068a0937a6f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDELLQyObPekPh7
XUsmfybS/gLlQ+wL0bgHWcqzzGIHAGcwgV+1Gxh7Q6AkACuToVGOlEgU3Q9VDNgQ
... (continúa sin modificar) ...
CcDEAor
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@elena-36be5.iam.gserviceaccount.com"
client_id = "117586238746856040628"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40elena-36be5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
