[firebase]
type = "service_account"
project_id = "elena-36be5"
private_key_id = "3c1451f3d53262402fa0d79e94369068a0937a6f"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDELLQyObPekPh7
XUsmfybS/gLlQ+wL0bgHWcqzzGIHAGcwgV+1Gxh7Q6AkACuToVGOlEgU3Q9VDNgQ
qoNPqlFhSBJ+IOKFRPpSGPgeHajTUi5bNRTf9gwHYnIVkRtEI+v6yckoOWJTkGuM
/zAv+0cJZkY4JrmWbraEM6kRF0viJQF5CIhiJKE+YVro6Lxouwwusq+ShhJL87mm
Gx0jIx0JCtbIwfEriN+3aHxCNZvxgQkNU2u0NPoN1ERgwQ+G1+tPDP3FDu5nGMaa
SjNwvOwI0H2rVBfN/JkFleJUxqrAvW8oHGkrKWrtbqTnbI5zZnn1BHvJQL+874km
eDR/Ftf5AgMBAAECggEAB2jeWgbMrM+KOSOkFOVI1r+WJal3+xbN5gYt1jZ2LehF
nYMHdchbF33NiMqSWspFMbbXVaVnYLmiWBfOq6XF2uAtZaLxl2HMeCkeBwotACVa
n6KMwixRlj5RS4/+aQeX0FJKlSi8tmYOL+ZMIEXUEC5zIMgSqrROE8Z9QGpiOP2G
nmGa9ELahQJtz/vYTFpr/0TM/FX9CQRhk2+6DTXubgSo15oOsseln9TlxsygmJ9C
G/JNjTAI+qH005n3uiVZfZWKT6x7k29c66MCYLzGFLZe2NgSuDGhxG/B98K7YKvd
jrZ49d5NL9WbXe3IMkRDLHM68L30PkO+dnPM5MpTIQKBgQDvVNXKOdS5aZQKBEJX
9ZXgx3Ft+ubN0dkMHHoMpWjStbxdhSMh/SFXUpwN5fDx4C2QQy1AaUtyv0V0O12m
/4MXD3e/Xi78fMfqdmd5GyJdj0U9mQLzpHG76qONDH+J45QxMNcui3MpnXWq/7AY
X84sB6D2+I/fr/X4nJieZTSwIQKBgQDR1md6PPbLVzSSdOpppuV6p28l1gm5eAF1
v8oLmR9ayYE9p7A0TYK6l8F/DhtIJKeQ6q7wxYTfO/L9v2m1bz1kAda+lID0eHH+
pKzOcx00v2HnC29YisV3oaw2VRgSTgfGfw5Y9HZZf5EFBN81u29OGWdA0f6b2WwG
i3mbB6wM2QKBgQCyMD2EdQ42ha7czlL+3jAazSNcuQOClgy9ga41ICotR3XZQzjn
I2nhc/YQOvTrgPcrg3h7jmnIIzR414Jgxbg6QR/s8RiWj+jgXguoFVW+xt7Mf9G8
yOCNAqOGbpm+dhxti2mKk/TINR3YlMntO9dq3LsxZdrotj+yPBU9SSizQQKBgD75
LUzOBvK3VRuu4rqaT7wji4O7XGfA0A9aY3Rfm71PQ+4Q6RyJNnZxHKzYuu9HsNIY
3C9914Z3I1FrpHnCzJW6x4uiXaEAlJVrLkE24sj1tpf0IpJb8y8X4ercVsEHkeXM
M64Wj34Efq0W7TXe7mRt00LswpBbC8RbDz+racLhAoGBAKbjFjm4TyvzAQjlayyb
9KzzKBBWe7AHuQRQsGziJb6KB0YF61h0Lbq8QK5mieNGsrKiXtLxC+c+34WMDCl2
aTbdisTXQ3h1gpNk/xyIFqcMAs+y7ttvL6aCzKQ1N/uUMBraxGHDY1j34U8IkQ7Q
VniSOLytypFz4NK8jCcDEAor
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@elena-36be5.iam.gserviceaccount.com"
client_id = "117586238746856040628"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40elena-36be5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
